spring:
  application:
    name: conveyor-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost/issuer}

server:
  port: 8080
  tomcat:
    max-part-count: 200

management:
  endpoints:
    web:
      exposure:
        include: health,info

conveyor:
  service:
    upload-dir: ./upload
    upload-enable: true
    oauth2-login-enable: true
    oauth2-resource-server-enable: true
    audit:
      enabled: true
      log-file: ./logs/conveyor-rest-audit.log
      max-file-size: 50MB
      max-history: 14
      total-size-cap: 1GB
      clean-history-on-start: false
    conveyor-log:
      log-file: ./logs/conveyor.log
      max-file-size: 100MB
      max-history: 14
      total-size-cap: 2GB
      clean-history-on-start: false
      level: DEBUG
    dashboard:
      default-watch-history-limit: 100
      default-conveyor-history-limit: 100
      default-ttl: "1 MINUTES"
      default-request-ttl: "100"
      default-admin-stop-timeout: "1 MINUTES"

logging:
  level:
    com.aegisql.conveyor: ${conveyor.service.conveyor-log.level:DEBUG}
