spring:
  application:
    name: conveyor-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost/issuer}

server:
  port: 8080
  tomcat:
    max-part-count: 200

management:
  endpoints:
    web:
      exposure:
        include: health,info

conveyor:
  service:
    upload-dir: ./upload
    upload-enable: true
    oauth2-login-enable: true
    dashboard:
      default-watch-history-limit: 100
      default-conveyor-history-limit: 100
      default-ttl: "1 MINUTES"
      default-request-ttl: "100"

logging:
  level:
    com.aegisql.conveyor: DEBUG

---
spring:
  config:
    activate:
      on-profile: linkedin
  security:
    oauth2:
      client:
        registration:
          linkedin:
            provider: linkedin
            client-id: ${LINKEDIN_CLIENT_ID}
            client-secret: ${LINKEDIN_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/linkedin"
            scope:
              - openid
        provider:
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            user-info-uri: https://api.linkedin.com/v2/userinfo
            jwk-set-uri: https://www.linkedin.com/oauth/openid/jwks
            user-name-attribute: sub
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://www.linkedin.com/oauth}

---
spring:
  config:
    activate:
      on-profile: demo
  security:
    oauth2:
      resourceserver:
        jwt:
          enabled: false

logging:
  level:
    com.aegisql.conveyor: INFO
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
