spring:
  application:
    name: conveyor-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost/issuer

server:
  tomcat:
    max-part-count: 200

management:
  endpoints:
    web:
      exposure:
        include: health,info

conveyor:
  service:
    upload-dir: ./upload
    dashboard:
      default-watch-history-limit: 100
      default-conveyor-history-limit: 100
      default-ttl: "1 MINUTES"
      default-request-ttl: "100"

logging:
  level:
    com.aegisql.conveyor: DEBUG

---
spring:
  config:
    activate:
      on-profile: demo
  security:
    oauth2:
      resourceserver:
        jwt:
          enabled: false

logging:
  level:
    com.aegisql.conveyor: INFO
